config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end  

  # def self.search(search)
  #   if search
  #     Tweet.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Tweet.all
  #   end
  # end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :tweets, dependent: :destory
  has_many :comments

  #ユーザ情報を検索するメソッドを追記
  def self.find_for_oauth(auth)#クラスメソッドクラスから使用可能
    user = User.where(uid: auth.uid, provider: auth.provider).first
     #where条件に合う全てのレコードを取得
     
    unless user #もしデーターベースに情報がなかったらユーザー情報を作成
      user = User.create(
        uid:        auth.uid,
        provider:   auth.provider,
        nickname:   auth.info.name,
        email:      User.dummy_email(auth),
        password:   Devise.friendly_token[0, 20]
      )
    end
  end

  private
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id]) }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbackController < Devise::OmniauthCallbacksController
  def facebook
    callback_form :facebook
  end

  def google_oauth2
    callback_from :google
  end


  private
  def callback_from(providefr)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
         #ログイン
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)      
      sign_in_and_redirect @user, event: :authentication

    else #新規登録
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:provider] = @user.provider
      session[:uid] = @user.uid
      redirect_to new_user_registration_sns_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mina De Tweet!!</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>



    <%= yield %>

    <footer>
      <p>&copy; Mina De Tweet!! 2020</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form.text_field :image, placeholder: "Image Url" %>
<%= form.text_area :text, placeholder: "text", rows: "10" %>
<%= form.submit "SEND" %>

app/views/tweets/_header.html.erb
  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/", id="sidebar-btn">Mina De Tweet!!</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_tweet_path, class: "post", id: "sidebar-btn" %>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "post", id: "sidebar-btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post', id: "sidebar-btn"%>
        </div>
      <% end %>
    </div>
  </header>

app/views/tweets/_tweet.html.erb
<div class= "content_post", style="background-image: url(<%= tweet.image %> );">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
        <li>
          <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
        </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user.id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/create.html.erb
  <%= render partial: "tweets/header" %>
<div class="contents row">
  <div class= "success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<%= render partial: "tweets/header" %>
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render partial: "tweets/header" %>
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        編集する
      </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/", id="sidebar-btn">Mina De Tweet!!</a></h1>
      <div class="user_nav grid-6">
        <span><%= current_user.nickname %>
          <ul class="user__info">
            <li>
              <%= link_to "マイページ", "/users/#{current_user.id}" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </span>
        <%= link_to "投稿する", new_tweet_path, class: "post", id: "sidebar-btn" %>
      </div>
    </div>
  </header>

  <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索‼", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="contents row">
    <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals:{ tweet: tweet} %>
    <% end %>
    <%= paginate(@tweets) %>
  </div>

<% else %>

  <header class="header">
    <div class="home-content2">
      <h1 class="page-title2"><a href="/", id="sidebar-btn">Mina De Tweet!!</a></h1>
    </div>
  </header>
  <div class="home-content wrapper big-bg" id="image-home">
    <h2 class="page-title">We're Happy By Tweet!!</h2>
    <p>気軽にシーンをシェアしません?楽しさを共有。</p>
    <div class="home-login">
      <%= link_to "ログイン", new_user_session_path, class: "post", id: "login-btn" %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post', id: "login-btn"%>
    </div>
  </div>

<% end %>

app/views/tweets/new.html.erb
<%= render partial: "tweets/header" %>
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        投稿する
      </h3>
      <%= form.text_field :image, placeholder: "画像のURLを入力して下さい。" %>
      <%= form.text_area :text, placeholder: "本文" , rows: "10" %>
      <%= form.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索‼", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<%= render partial: "tweets/header" %>
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/tweet/#{@tweet.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true, id: "new_comment") do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "textbox" %>
        <%= form.submit "SEND", class: "form__submit" %>
      <% end %>
    <% else %>
      <strong><p>*** コメントの投稿には新規登録/ログインが必要です ***</p></strong>
    <% end %>
    
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/user/#{comment.user_id}" %>:</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>    
    </div>    
  </div>
</div>  

app/views/tweets/update.html.erb
<%= render partial: "tweets/header" %>
<div class="contents row">
  <div class= "success">
    <h3>
      更新が完了しました
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "tweets/header" %>
<div class="contents row">
  <p class="mypage-title"><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>